raw_data = [
  "my_gauge{_ws_=\"test_ws\",_ns_=\"promcompat\"}", "", "",
  "my_counter{_ws_=\"test_ws\",_ns_=\"promcompat\"}", "", ""
]

aggregate_functions = [
  "sum(my_gauge{_ws_=\"test_ws\",_ns_=\"promcompat\"})", "0.0001", "",
  "sum by (mode) (my_gauge{_ws_=\"test_ws\",_ns_=\"promcompat\"})", "0.0001", "",
  "avg by (instance) (my_gauge{_ws_=\"test_ws\",_ns_=\"promcompat\"})", "0.0001", "",
  "max without (instance) (my_gauge{_ws_=\"test_ws\",_ns_=\"promcompat\"})", "0.0001", "",
  "min(my_gauge{_ws_=\"test_ws\",_ns_=\"promcompat\"})", "0.0001", "",
  "count(my_gauge{_ws_=\"test_ws\",_ns_=\"promcompat\"})", "", ""
]

topk = [
  "topk(2, my_gauge{_ws_=\"test_ws\",_ns_=\"promcompat\"})", "0.0001", "",
  "bottomk(2, my_gauge{_ws_=\"test_ws\",_ns_=\"promcompat\"})", "0.0001", ""
]

rate_functions = [
  "rate(my_counter{_ws_=\"test_ws\",_ns_=\"promcompat\"}[1m])", "0.1%", "",
  "sum(rate(my_counter{_ws_=\"test_ws\",_ns_=\"promcompat\"}[5m]))", "0.1%", "",
  "increase(my_counter{_ws_=\"test_ws\",_ns_=\"promcompat\"}[5m])", "0.1%", "",
  "avg_over_time(my_gauge{_ws_=\"test_ws\",_ns_=\"promcompat\"}[5m])", "0.0001", ""
]

binary_operators = [
  "my_gauge{_ws_=\"test_ws\",_ns_=\"promcompat\"} + my_gauge{_ws_=\"test_ws\",_ns_=\"promcompat\"}", "0.0001", "",
  "my_counter{_ws_=\"test_ws\",_ns_=\"promcompat\"} > 1000", "", ""
]
