[package]
name = "filodb_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
nom = "7.1.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
regex = "1.10.5"
tantivy = "0.22.0"
thiserror = "1.0.62"

[dev-dependencies]
bytes = "1.6.1"
